apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: parflesh-operators-deploy-template
metadata:
  annotations:
  name: parflesh-operators-deploy
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          marketplace.operatorSource: ${NAME}
      template:
        metadata:
          name: ${NAME}
          namespace: ${NAMESPACE}
          labels:
            marketplace.operatorSource: ${NAME}
        spec:
          containers:
            - resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
              readinessProbe:
                exec:
                  command:
                    - grpc_health_probe
                    - '-addr=localhost:50051'
                initialDelaySeconds: 5
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: registry-server
              livenessProbe:
                exec:
                  command:
                    - grpc_health_probe
                    - '-addr=localhost:50051'
                initialDelaySeconds: 10
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              securityContext:
                capabilities:
                  drop:
                    - MKNOD
              ports:
                - name: grpc
                  containerPort: 50051
                  protocol: TCP
              imagePullPolicy: Always
              terminationMessagePolicy: File
              image: ${IMAGE}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      ports:
        - name: grpc
          protocol: TCP
          port: 50051
          targetPort: 50051
      selector:
        marketplace.operatorSource: ${NAME}
  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      address: '${NAME}.${NAMESPACE}.svc:50051'
      displayName: ${DISPLAY_NAME}
      icon:
        base64data: ''
        mediatype: ''
      publisher: ${PUBLISHER}
      sourceType: grpc
parameters:
  - name: NAME
    required: true
    value: "parflesh-operators"
  - name: IMAGE
    value: "quay.io/parflesh/parflesh-operators:latest"
  - name: NAMESPACE
    value: "openshift-marketplace"
  - name: DISPLAY_NAME
    value: "ParFlesh"
  - name: PUBLISHER
    value: "ParFlesh"